### ISSUE TITLE
Current PNMLFW url

### ISSUE THREAD

**Issue by yanntm** [YuriBlankenstein/pnmlframework.io#1]
Hi,
just to tell you the latest update site for PNMLFW is available from this URL : https://lip6.github.io/pnmlframework/
As this is an update site, clicking gives a 404, but e.g. https://lip6.github.io/pnmlframework/content.jar will work, or adding it to eclipse update site list works.

We've switched to continuous release and versioning and are in 2.14+ generation, but if you would like us to publish an artifact with a proper release version tag, and maybe push it to maven central etc, please raise an issue against our repo, we haven't done it in a long time, but we can do that and release e.g. 2.15. 
PNMLFW is maintained (mostly) and updated (slowly) so we are curious as to why you would want a 2.12 repository up. 
Is it due to Java11 requirement in recent versions ?

Best regards 
Yann (one of the maintainers on PNMLFW)

**Comment by YuriBlankenstein** [comment]
Hi Yann,

Thank you for your message. I was aware of the new update-site, but you're right that the Java11 requirement was the reason for me to host this copy of the 2.2.12 update-site.

As we had an older prototype which was based on Eclipse Neon, we could not use Java11 (Neon supports up to and including Java8). This was failing our CI/CD for that prototype and therefore I chose to host version 2.2.12 myself.

Kind regards,
Yuri

**Comment by yanntm** [comment]
Hi,

Ok, I'm kind of worried that this Java 11 requirement might cause issues for other users, we did the switch due to now lower availability of JDK8, but it might still be too soon. Especially since the code base does not really care, it runs on 1.5+ I believe. So I played around with maven options to compile with target 1.8 again on  the main repo.

So, sorry for the inconvenience it caused you, but the update site is back to 1.8 execution environment requirements.
This still raises issues on stabler releases though, as I guess your code broke without warning, and you had to diagnose and then build this workaround, I'll look into it.

Please post an issue on the https://github.com/lip6/pnmlframework/issues main repo if you have any other problems, this way we can solve it for other users too.

best regards
Yann

**Comment by yanntm** [comment]
as side note, we also tagged a new 2.2.15 release, supporting Java 1.8 but otherwise up to date.
